version: '3'
services:
  redis:
    image: redis
  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
      - db
